name: Sonar
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 14 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Build with npm
        run: |
          npm ci
          npm run build --if-present
      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
        with:
          args: >
            -Dsonar.organization=mastercard
            -Dsonar.projectName=insomnia-plugin-mastercard
            -Dsonar.projectKey=Mastercard_insomnia-plugin-mastercard
            -Dsonar.sources=./src -Dsonar.host.url=https://sonarcloud.io 
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
